// Generated by CoffeeScript 1.7.1
var ReactCompiler, transform;

transform = require('coffee-react-transform');

module.exports = ReactCompiler = (function() {
  ReactCompiler.prototype.brunchPlugin = true;

  ReactCompiler.prototype.type = 'javascript';

  ReactCompiler.prototype.extension = 'cjsx';

  ReactCompiler.prototype.pattern = /\.cjsx/;

  function ReactCompiler(config) {
    var _ref, _ref1, _ref2;
    this.config = config;
    this.includeHeader = ((_ref = this.config) != null ? (_ref1 = _ref.plugins) != null ? (_ref2 = _ref1.react) != null ? _ref2.autoIncludeCommentBlock : void 0 : void 0 : void 0) === true;
  }

  ReactCompiler.prototype.compile = function(params, callback) {
    var err, output, source;
    source = this.includeHeader ? "# @cjsx React.DOM \n" + params.data : params.data;
    try {
      output = transform(source);
    } catch (_error) {
      err = _error;
      console.log("ERROR", err);
      return callback(err.toString());
    }
    return callback(null, {
      data: output
    });
  };

  return ReactCompiler;

})();
